config:
  csvFilesFolder: "csv"
  csvEncode: "ISO-8859-1"
  csvSeparator: ";"
  rdfFolder: "rdf"
  rdfFormat: "NTRIPLE"
  ontologyFormat: "N3"
  writeToFile: true
  singleRdfOutputFile: true
  resourcesPerFile: 100
  processWhenStarted: true
  
  
